apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  labels:
    app: eureka-server
spec:
  type: NodePort
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 8761   # Fixed node port
      protocol: TCP
      name: http
  selector:
    app: eureka-server
