apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  labels:
    app: eureka-service
spec:
  type: NodePort
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30076   # in allowed range
      protocol: TCP
      name: http
  selector:
    app: eureka-service
