apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  labels:
    app: eureka-server
spec:
  type: LoadBalancer  # NodePort for local testing
  ports:
    - port: 8761
      targetPort: 8761
      protocol: TCP
      name: http
  selector:
    app: eureka-server