apiVersion: v1
kind: Service
metadata:
  name: eureka-nodeport
spec:
  type: NodePort
  selector:
    app: service-registry
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      nodePort: 30861  # You can choose any port between 30000–32767
