apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cm
data:
  # Eureka cluster endpoints (3-node cluster with headless service `eureka`)
  eureka_service_address: "http://eureka-0.eureka.default.svc.cluster.local:8761/eureka,http://eureka-1.eureka.default.svc.cluster.local:8761/eureka,http://eureka-2.eureka.default.svc.cluster.local:8761/eureka"
