server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: eureka-service  # Kubernetes service name
  client:
    registerWithEureka: false # Eureka server does not register itself
    fetchRegistry: false      # Does not fetch registry (it's the server)
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/  # Self-registration URL